service: shopping-lists

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-aws-documentation

custom:
  documentation:
    api:
      info:
        version: "2"
        title: shopping lists api
    models:
      - name: getShoppingListResponse
        contentType: "application/json"
        schema:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            description:
              type: string
            items:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                  quantity:
                    type: number
                  unit:
                    type: string
      - name: getShoppingListsResponse
        contentType: "application/json"
        schema:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              description:
                type: string
              items:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    price:
                      type: number
                    quantity:
                      type: number
                    unit:
                      type: string
      - name: shoppingListRequestBody
        contentType: "application/json"
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            items:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
                  quantity:
                    type: number
                  unit:
                    type: string

functions:
  getShoppingLists:
    handler: app/handler.getShoppingLists
    events:
      - http:
          path: shoppingLists
          method: get
          cors: true
          documentation:
            summary: "Get shopping lists"
            description: "Get all the shopping lists"
            contentType: "application/json"
            methodResponses:
              - statusCode: 200
                responseModels:
                  application/json: getShoppingListsResponse

  getSingleShoppingList:
    handler: app/handler.getSingleShoppingList
    events:
      - http:
          path: shoppingLists/{id}
          method: get
          cors: true
          documentation:
            summary: "Get a single shopping list"
            contentType: "application/json"
            pathParams:
              - name: "id"
                description: "The id of a single shopping list"
                schema:
                  type: "string"
                  pattern: "^[-a-z0-9_]+$"
            methodResponses:
              - statusCode: 200
                responseModels:
                  application/json: getShoppingListResponse
  createShoppingList:
    handler: app/handler.createShoppingList
    events:
      - http:
          path: shoppingLists
          method: post
          cors: true
          documentation:
            summary: "create a shopping list"
            description: "create a shopping list"
            contentType: "application/json"
            requestModels:
              application/json: shoppingListRequestBody
            methodResponses:
              - statusCode: 201
  updateShoppingList:
    handler: app/handler.updateShoppingList
    events:
      - http:
          path: shoppingLists/{id}
          method: put
          cors: true
          documentation:
            summary: "update a shopping list"
            description: "update a shopping list"
            contentType: "application/json"
            pathParams:
              - name: "id"
                description: "The id of a single shopping list"
                schema:
                  type: "string"
                  pattern: "^[-a-z0-9_]+$"
            requestModels:
              application/json: shoppingListRequestBody
            methodResponses:
              - statusCode: 200
                responseModels:
                  application/json: getShoppingListResponse
  deleteShoppingList:
    handler: app/handler.updateShoppingList
    events:
      - http:
          path: shoppingLists/{id}
          method: delete
          cors: true
          documentation:
            summary: "delete a shopping list"
            description: "delete a shopping list"
            contentType: "application/json"
            pathParams:
              - name: "id"
                description: "The id of a single shopping list"
                schema:
                  type: "string"
                  pattern: "^[-a-z0-9_]+$"
            requestModels:
              application/json: shoppingListRequestBody
            methodResponses:
              - statusCode: 204